USE CentroToelettatura;

INSERT INTO Operatore (nome, cognome, specializzazione, numero_telefono, livello_esperienza) VALUES ('Alessandro','Rossi','Cani grandi','3964153544','senior');
INSERT INTO Operatore (nome, cognome, specializzazione, numero_telefono, livello_esperienza) VALUES ('Francesca','Colombo','Toelettatura completa','3752985847','senior');
INSERT INTO Operatore (nome, cognome, specializzazione, numero_telefono, livello_esperienza) VALUES ('Simone','Greco','Toelettatura completa','3218446335','intermedio');
INSERT INTO Operatore (nome, cognome, specializzazione, numero_telefono, livello_esperienza) VALUES ('Laura','Greco','Cani grandi','3631834117','intermedio');
INSERT INTO Operatore (nome, cognome, specializzazione, numero_telefono, livello_esperienza) VALUES ('Davide','Romano','Dermatologia','3509175195','junior');

INSERT INTO Proprietario (nome, cognome, data_nascita, contatto) VALUES ('Luca','Colombo','2001-01-21','3318045627');
INSERT INTO Proprietario (nome, cognome, data_nascita, contatto) VALUES ('Chiara','De Luca','1971-01-23','3379927948');
INSERT INTO Proprietario (nome, cognome, data_nascita, contatto) VALUES ('Chiara','Ricci','1996-05-01','3205696017');
INSERT INTO Proprietario (nome, cognome, data_nascita, contatto) VALUES ('Martina','Bruno','1992-04-12','3285598205');
INSERT INTO Proprietario (nome, cognome, data_nascita, contatto) VALUES ('Davide','Rossi','1998-11-26','3682814999');
INSERT INTO Proprietario (nome, cognome, data_nascita, contatto) VALUES ('Matteo','Greco','1998-11-17','3348330022');
INSERT INTO Proprietario (nome, cognome, data_nascita, contatto) VALUES ('Giulia','Bruno','1998-01-13','3421627973');
INSERT INTO Proprietario (nome, cognome, data_nascita, contatto) VALUES ('Laura','Conti','1997-09-24','3428783061');
INSERT INTO Proprietario (nome, cognome, data_nascita, contatto) VALUES ('Sara','Esposito','2005-06-03','3710981086');
INSERT INTO Proprietario (nome, cognome, data_nascita, contatto) VALUES ('Alessandro','Colombo','1987-04-08','3828555393');

INSERT INTO Animale (razza, tipologia_pelo, carattere, taglia, dermatiti, id_proprietario) VALUES ('cane','medio','calmo','grande',1,7);
INSERT INTO Animale (razza, tipologia_pelo, carattere, taglia, dermatiti, id_proprietario) VALUES ('cane','corto','aggressivo','grande',0,9);
INSERT INTO Animale (razza, tipologia_pelo, carattere, taglia, dermatiti, id_proprietario) VALUES ('cane','lungo','calmo','piccola',1,10);
INSERT INTO Animale (razza, tipologia_pelo, carattere, taglia, dermatiti, id_proprietario) VALUES ('gatto','corto','aggressivo','piccola',0,9);
INSERT INTO Animale (razza, tipologia_pelo, carattere, taglia, dermatiti, id_proprietario) VALUES ('gatto','corto','timido','grande',1,4);
INSERT INTO Animale (razza, tipologia_pelo, carattere, taglia, dermatiti, id_proprietario) VALUES ('gatto','corto','timido','grande',0,10);
INSERT INTO Animale (razza, tipologia_pelo, carattere, taglia, dermatiti, id_proprietario) VALUES ('cane','medio','calmo','grande',1,10);
INSERT INTO Animale (razza, tipologia_pelo, carattere, taglia, dermatiti, id_proprietario) VALUES ('cane','lungo','aggressivo','piccola',0,3);
INSERT INTO Animale (razza, tipologia_pelo, carattere, taglia, dermatiti, id_proprietario) VALUES ('gatto','lungo','giocherellone','piccola',1,5);
INSERT INTO Animale (razza, tipologia_pelo, carattere, taglia, dermatiti, id_proprietario) VALUES ('gatto','lungo','agitato','media',1,5);
INSERT INTO Animale (razza, tipologia_pelo, carattere, taglia, dermatiti, id_proprietario) VALUES ('cane','medio','calmo','media',1,5);
INSERT INTO Animale (razza, tipologia_pelo, carattere, taglia, dermatiti, id_proprietario) VALUES ('cane','corto','calmo','media',0,6);
INSERT INTO Animale (razza, tipologia_pelo, carattere, taglia, dermatiti, id_proprietario) VALUES ('gatto','lungo','aggressivo','grande',0,2);
INSERT INTO Animale (razza, tipologia_pelo, carattere, taglia, dermatiti, id_proprietario) VALUES ('cane','lungo','agitato','media',1,10);
INSERT INTO Animale (razza, tipologia_pelo, carattere, taglia, dermatiti, id_proprietario) VALUES ('gatto','medio','giocherellone','grande',0,2);

INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-10-30','14:00:00','16:00:00','2:00:00','annullato',1,13);
INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-06-11','13:00:00','15:00:00','2:00:00','annullato',4,4);
INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-05-04','10:00:00','12:00:00','2:00:00','prenotato',3,10);
INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-03-25','13:00:00','14:00:00','1:00:00','annullato',2,14);
INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-03-25','09:00:00','11:00:00','2:00:00','prenotato',5,7);
INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-12-13','15:00:00','17:00:00','2:00:00','completo',2,3);
INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-03-06','12:00:00','13:00:00','1:00:00','completo',4,14);
INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-11-03','15:00:00','17:00:00','2:00:00','completo',4,15);
INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-04-11','09:00:00','10:00:00','1:00:00','prenotato',5,15);
INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-06-30','13:00:00','14:00:00','1:00:00','prenotato',3,5);
INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-07-30','09:00:00','10:00:00','1:00:00','annullato',1,4);
INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-10-27','14:00:00','16:00:00','2:00:00','completo',2,10);
INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-09-15','15:00:00','17:00:00','2:00:00','prenotato',4,7);
INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-08-01','12:00:00','14:00:00','2:00:00','prenotato',5,3);
INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-01-01','11:00:00','12:00:00','1:00:00','completo',2,11);
INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-08-24','11:00:00','12:00:00','1:00:00','completo',5,2);
INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-12-06','10:00:00','12:00:00','2:00:00','prenotato',5,1);
INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-02-19','09:00:00','10:00:00','1:00:00','completo',4,2); 
INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-12-19','15:00:00','17:00:00','2:00:00','annullato',4,4);
INSERT INTO Appuntamenti (data_appuntamento, ora_inizio, ora_fine, durata, stato, id_operatore, id_animale) VALUES ('2025-07-26','12:00:00','14:00:00','2:00:00','completo',2,9);

INSERT INTO Pagamento (data_pagamento, importo, metodo_pagamento, id_appuntamento) VALUES ('2025-07-04',25,'contanti',18);
INSERT INTO Pagamento (data_pagamento, importo, metodo_pagamento, id_appuntamento) VALUES ('2025-10-31',20,'contanti',4);
INSERT INTO Pagamento (data_pagamento, importo, metodo_pagamento, id_appuntamento) VALUES ('2025-05-14',40,'carta',12);
INSERT INTO Pagamento (data_pagamento, importo, metodo_pagamento, id_appuntamento) VALUES ('2025-01-16',20,'bancomat',12);
INSERT INTO Pagamento (data_pagamento, importo, metodo_pagamento, id_appuntamento) VALUES ('2025-11-15',50,'carta',17);
INSERT INTO Pagamento (data_pagamento, importo, metodo_pagamento, id_appuntamento) VALUES ('2025-01-10',45,'bancomat',14);
INSERT INTO Pagamento (data_pagamento, importo, metodo_pagamento, id_appuntamento) VALUES ('2025-10-14',35,'bancomat',7);
INSERT INTO Pagamento (data_pagamento, importo, metodo_pagamento, id_appuntamento) VALUES ('2025-12-25',50,'bancomat',20);
INSERT INTO Pagamento (data_pagamento, importo, metodo_pagamento, id_appuntamento) VALUES ('2025-09-14',35,'bancomat',3);
INSERT INTO Pagamento (data_pagamento, importo, metodo_pagamento, id_appuntamento) VALUES ('2025-01-26',30,'carta',14);
INSERT INTO Pagamento (data_pagamento, importo, metodo_pagamento, id_appuntamento) VALUES ('2025-08-02',45,'contanti',17);
INSERT INTO Pagamento (data_pagamento, importo, metodo_pagamento, id_appuntamento) VALUES ('2025-03-08',45,'carta',17);
INSERT INTO Pagamento (data_pagamento, importo, metodo_pagamento, id_appuntamento) VALUES ('2025-02-02',30,'carta',7);
INSERT INTO Pagamento (data_pagamento, importo, metodo_pagamento, id_appuntamento) VALUES ('2025-03-20',40,'carta',7);
INSERT INTO Pagamento (data_pagamento, importo, metodo_pagamento, id_appuntamento) VALUES ('2025-11-30',35,'contanti',7);

INSERT INTO Trattamento (tipologia) VALUES ('Lavaggio');
INSERT INTO Trattamento (tipologia) VALUES ('Taglio');
INSERT INTO Trattamento (tipologia) VALUES ('Asciugatura');
INSERT INTO Trattamento (tipologia) VALUES ('Spazzolatura');
INSERT INTO Trattamento (tipologia) VALUES ('Trattamento antiparassitario');
INSERT INTO Trattamento (tipologia) VALUES ('Pulizia orecchie');

INSERT INTO Prodotto (quantita_disponibili) VALUES (46);
INSERT INTO Prodotto (quantita_disponibili) VALUES (76);
INSERT INTO Prodotto (quantita_disponibili) VALUES (92);
INSERT INTO Prodotto (quantita_disponibili) VALUES (66);
INSERT INTO Prodotto (quantita_disponibili) VALUES (71);
INSERT INTO Prodotto (quantita_disponibili) VALUES (53);
INSERT INTO Prodotto (quantita_disponibili) VALUES (16);
INSERT INTO Prodotto (quantita_disponibili) VALUES (38);

INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (14,1);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (10,4);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (16,2);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (1,1);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (15,5);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (16,5);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (11,1);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (14,5);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (2,2);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (18,2);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (7,2);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (13,4);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (6,4);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (15,6);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (4,2);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (13,2);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (10,3);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (2,3);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (11,3);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (17,1);
INSERT INTO R_Include (id_appuntamento, id_trattamento) VALUES (17,3); 

INSERT INTO Utilizza (id_trattamento, id_prodotto, quantita_usata) VALUES (3,5,1);
INSERT INTO Utilizza (id_trattamento, id_prodotto, quantita_usata) VALUES (2,7,4);
INSERT INTO Utilizza (id_trattamento, id_prodotto, quantita_usata) VALUES (2,5,4);
INSERT INTO Utilizza (id_trattamento, id_prodotto, quantita_usata) VALUES (5,8,5);
INSERT INTO Utilizza (id_trattamento, id_prodotto, quantita_usata) VALUES (4,1,5);
INSERT INTO Utilizza (id_trattamento, id_prodotto, quantita_usata) VALUES (6,5,4);
INSERT INTO Utilizza (id_trattamento, id_prodotto, quantita_usata) VALUES (3,2,5);
INSERT INTO Utilizza (id_trattamento, id_prodotto, quantita_usata) VALUES (1,1,2);
INSERT INTO Utilizza (id_trattamento, id_prodotto, quantita_usata) VALUES (1,3,4);
INSERT INTO Utilizza (id_trattamento, id_prodotto, quantita_usata) VALUES (4,5,4);
INSERT INTO Utilizza (id_trattamento, id_prodotto, quantita_usata) VALUES (2,4,4);
INSERT INTO Utilizza (id_trattamento, id_prodotto, quantita_usata) VALUES (5,6,1);